### ISSUE TITLE
Cambio branding a LACChain EOSIO

### ISSUE THREAD

**Issue by ldrojas** [lacchain/eosio.lacchain.net#14]
- [x] Logo #13
- [x] Definición identidad visual #15 @murillojorge 
- [x] Cambios nombres en repositorios #16
- [x] Cambios re-direccionamientos de otros sitios y links en website y guías de Latamlink por LACChain EOSIO #17
