### ISSUE TITLE
Nuevo sitio

### ISSUE THREAD

**Issue by ldrojas** [lacchain/eosio.lacchain.net#2]
Rediseño completo del sitio de LACChain EOSIO.

Proceso:

- [x] Redacción de contenidos @ldrojas 
- [x] Consolidar ambos sitios @AngeloCG97 #1
- [x] Crear drafts de los contenidos para las imágenes @ldrojas #4
- [x] Recolectar los íconos @ldrojas #5
- [x] Diseño visual del sitio #3 @Johannayee 
- [x] Preparar imágenes del sitio @Johannayee  #6
- [x] Definir flujo para contacto @ldrojas @AngeloCG97 #18
- [x] Formulario de contacto @AngeloCG97 #20
- [x] Desarrollo del sitio @AngeloCG97 
  - [x] Homepage #7
  - [x] About #8
  - [x] Contacto #9
- [x] Test del sitio @ldrojas #10
  - [x] ES
  - [x] EN
